---
title: 'Assignment 3'
subtitle: "Data Science for Biodata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAbElEQVR4Xs2RQQrAMAgEfZgf7W9LAguybljJpR3wEse5JOL3ZObDb4x1loDhHbBOFU6i2Ddnw2KNiXcdAXygJlwE8OFVBHDgKrLgSInN4WMe9iXiqIVsTMjH7z/GhNTEibOxQswcYIWYOR/zAjBJfiXh3jZ6AAAAAElFTkSuQmCCmedical Informatics (BMIN5030)"
format: 
  html:
    theme: lumen
editor: visual
embed-resources: true
execute: 
  warning: false
---

------------------------------------------------------------------------

### Instructions

-   Download the qmd version of this file
-   Complete the questions below in RStudio using the qmd file as a template
-   Replace the sample text after each question with your answers
-   Save the qmd document as Assignment3\_*YOUR LAST NAME*.qmd
-   Render the qmd file as an HTML
-   Turn in completed Assignment3\_*YOUR LAST NAME*.html file in Canvas under Assignments -\> Assignment 3
-   Your assignment **must** be in html format or it will not be graded
-   Grades will be assigned according to point scheme below and computed as a percentage of total possible points
-   Lateness policy: If an urgent and unforeseen circumstance comes up and you need an extension to turn in an assignment, please contact Anurag, Brielin, Chloe and Max as soon as possible. Unless there is an arrangement in place, late assignments will be scored as follows:
    -   25% of total score if 1 day late
    -   50% of total score if 2 days late
    -   75% of total score if 3 days late
    -   Assignment will not be graded if 4 or more days late
-   DUE DATE: 10/1/25 11:59pm

### Final Project - Topic

Fork the [Final Project Repository](https://github.com/bcbg-bio/BMIN5030_Final_Project) to your GitHub account, and pull this forked repository as a new project on your local computer by using the *Project* menu in the upper-right-hand corner of RStudio, selecting a *New Project*, creating it via *Version Control* -\> *Git* -\> and entering your GitHub repository (remember to append `.git` to the copied `url`). You can work on your final project from your computer, and easily push updates to your GitHub account, where the final version will be saved. A *Git* tab will be available that you can use to *Pull*, *Commit*, and *Push* changes between your local version and that on GitHub without having to use the command line.

1.  In 2-3 sentences, describe what question you will answer for your final project and what data you will use. There is a list of [publicly available data sources](https://github.com/bcbg-bio/BMIN5030/blob/master/public_datasets.md) on GitHub that you can look through if you are having difficulty identifying a dataset to use. If you'd like help to pick a topic, please let Blanca know soon. *(2 points)*

> Replace this text with your answer

2.  What two faculty/staff (name, title, division/department) have you met or are planning to meet to discuss your project? *(2 points)*

> Replace this text with a list two faculty/staff (name, title, division/department)

### Cleaning and Transforming data, Descriptive Statistics and Regression

3.  Install and load the [`nycflights13`](https://nycflights13.tidyverse.org) package to do this problem. This package includes the `flights` tibble, which contains information on 336,776 flights that departed from New York City in 2013. Use `dplyr` to answer the following questions by inserting code below each bullet to provide the answer directly. Assume that the three airports with departing flights (EWR, JFK and LGA) are the ones with flights originating from NYC. To find out more about the variables available, it is helpful to consult the Reference Manual you can find in the [CRAN entry](https://cloud.r-project.org/web/packages/nycflights13/index.html) for the package. *(10 points)*
    -   How many flights had Philadelphia International Airport (PHL) as destination? Which carrier had the most departing flights to Philadelphia? Note: you can look up the carriers by name using the `airlines` tibble.
    -   Of the flights that departed from JFK with scheduled departure between 0500hr and 2000hr, how many had destinations beginning or ending with the letter C? Which carriers flew these flights, and how many of these flights corresponded to each carrier?
    -   List the top 10 destinations based on having the greatest mean departure delay (it is acceptable to remove missing values from this calculation), along with the number of flights to each of these destinations. Next, list the destination that Frontier Airlines had the most flights to in a given month, along with the corresponding number of flights.
    -   Is there a linear relationship between the departure delay (dep_delay) and distance of the flight (distance)? The answer should show a plot and use one sentence to address this question qualitatively. That is, there is no need to create a model to formally evaluate a relationship.
    -   Was the median arrival delay (arr_delay) related to the time of departure (dep_time)? The answer should show a plot and use two sentences to address this question qualitatively.
4.  Load the RDS file located [here](https://github.com/bcbg-bio/BMIN5030/blob/master/DataFiles/brfss2022_cleaned.rds) which contains the a cleaned subset of the [2022 BRFSS dataset](https://www.cdc.gov/brfss/annual_data/annual_2022.html) as described in this [data dictionary](https://github.com/bcbg-bio/BMIN5030/blob/master/DataFiles/BRFSS2022_DataDictionary.md) to answer the following questions. We will explore some of the data and create some regression models. NOTE: We are analyzing raw BRFSS data without taking the survey design into account, and thus, our results are not representative of the US population sampled. *(10 points)*
    -   Load the dataset using `read_rds()`, while recalling that the link used must point to the *raw* data in GitHub. How many people reported having tested negative and positive to COVID as contained in the `covidpos` variable? How many people reported ever having had a depressive disorder as contained in the `depression` variable? What were the possible responses to the `genhealth` variable, which corresponded to the question "Would you say that in general your health is:...", and how many responses were there to each level?
    -   Ignore the missing responses to any variable that is being considered while you answer the following. Do you notice any trends in the distribution of responses to `covidpos` according to `race` or `income`? What about for `genhealth`? Respond by using plots and a few sentences. There is no need to create any models.
    -   Perform bivariate analysis for the `race`, `sex`, `age`, `sleep` and `exercise` variables as predictors and `depression` as outcome. Do not relevel or transform variables. Include appropriate plots that look at the pairwise relationships between the outcomes and each predictor and create regression models to model the bivariate relationship between each outcome and each predictor. Which of the variables are associated with `depression`?
    -   Create a multivariable regression model for `depression` using `sex`, `race`, `age`, `sleep`, and `exercise` as predictors. What variables are significantly associated with `depression` in the combined model? Are there substantial differences compared to the bivariate models? What does this indicate?
    -   Consider a new multivariable model in which `age`, `race`, and an interaction term between them are predictors of `depression`. Is there any evidence of effect modification? Create a descriptive plot of the data distributions that helps to visualize why there is or is not effect modification. Hint: use `facet_wrap()` to help visualize the three variables involved.
